### ISSUE TITLE
Sync issue - Audio/Video

### ISSUE THREAD

**Issue by Tale-Spin** [AntonyCorbett/OnlyR#24] opened 2018-12-21 14:37 UTC
**Describe the bug**
Audio is ahead of video when playing videos in JW Library app when Only-R is open.  Sync is fine when Only-R is not open.  Recorder does not need to be recording - only open on the desktop.  Sometimes the sync problem clears up if I close and reopen JW Library.

**To Reproduce**
3. See error

**Expected behavior**
I updated Realtek audio driver which seemed to fix the problem with JW Library but it recurred when opening Only-R.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Other important information about your environment

**Comment by AntonyCorbett** [comment] 2018-12-29 14:50
Closing for now as there is no response.

**Comment by westhouseit** [comment] 2020-03-08 21:56
I can confirm that we're having this issue as well. To replicate:

1. Open JW Library, download the latest broadcasting.
2. Open OnlyR
3. Start playing broadcasting.

I'm not sure where the issue lies but hopefully we can start to narrow down the true cause.

One thing we tried was scrubbing through the video timeline and back to the beginning. This appeared to reduce the lip sync issue to about 1/4 of a second.

The laptop here is an Asus using a Realtek chipset and one of those stupid combo headphone/mic ports. I'll try to get some more details the next time I can get access.

Some other things I'd like to try are:
1. Test with another audio recording program, e.g. Audacity.
2. Run the above steps on different computers and compare similarities/differences.
3. Test with an USB audio device.

**Comment by richfrantz** [comment] 2020-03-08 21:58
It's jwl

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by westhouseit** [comment] 2020-03-08 22:00
@richfrantz have you submitted the code fix to the brothers so they can implement it?

**Comment by richfrantz** [comment] 2020-03-08 22:03
Sniff. Sniff. Is that snark I smell? To answer your question, no, but we've been dealing with this sync issue for well over a year.
Download a video, not stream, and play it through JWL, sync issue.
Play that same video through onlym, or VLC, no sync issue.
That's why I said what I said.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by westhouseit** [comment] 2020-03-08 22:22
Sorry, perhaps a bit. I'm just used to people claiming they know the reason for a software issue when they don't have access to or a deep enough understanding of the systems involved.

What you're referring to as JW Library being the cause is actually a correlation, not a causation. For example, do we know whether JWL is doing sync calculations (to support streaming) that could perhaps be thrown out by the Realtek drivers returning bad data when OnlyR is running? I certainly don't, so I can't assume on a system like Windows with a massive number of interconnected systems that one piece of software is clearly at fault when I can't even run a debugger for myself. So there certainly is a strong correlation, but until the actual core issue is identified and resolved how can we know the cause?

P.S. The example above is completely hypothetical and just there to illustrate a point.

**Comment by richfrantz** [comment] 2020-03-08 22:28
No worries, I'm a developer too, for a living, when I get home it's the last thing I want to do, so for me my "correlation" is proof enough.

My "theory" is that it's the encoder, onlym and VLC use the same one I can't remember the name and I'm not going to go look it up FFmpeg or something like that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by AntonyCorbett** [comment] 2020-03-09 08:49
@westhouseit Thanks for your report. Some questions:

1. Please would you confirm that JWL audio/video sync is ok when OnlyR is _not_ running. 
2. Assuming 1 above is the case, what happens when OnlyR is launched _after_ JWL playback.
3. Please confirm that simply launching OnlyR (without starting a recording) is all that is needed to induce the problem.
4. Does the video lag behind the audio or vice versa (not always easy to tell)?
5. Does the problem exist even when OnlyR is minimized?
6. What CPU % does OnlyR use when open (but not recording)?
7. If you use 3rd party anti-virus tools, could you temporarily disable them to determine if they contribute to the problem?
8. Does it make a difference whether JWL is also rendering the video on a secondary monitor?
9. Please launch OnlyR with the --nogpu command-line option. This will ensure that OnlyR makes no use of GPU rendering. Does the problem still exist?

Although it's certainly true that JWL audio/video sync is a very common problem, I have reopened this issue in case we can discover something new!

Thanks for your help.

Kind regards
Antony

**Comment by Tale-Spin** [comment] 2020-03-11 01:15
This may be irrelevant, but we used to have three congregations at our hall, each with its own user account in Windows 10.  The sync issue was intermittent for all three user accounts.  After the reorganization in November 2019 we only have one congregation at our hall.  Since deleting the other two user accounts the sync problem seems to have cleared up.  We usually run JWL, Only-R, Only-T, Only-M (occasionally) and sometimes JWL Helper for a song.  We sometimes use Firefox to stream audio of the Scriptures for the Cong, Bible Study.  Even with everything open, the sync issue has cleared up since deleting those two user accounts.

**Comment by westhouseit** [comment] 2020-03-11 10:42
Interesting. I'll be doing some more tests tomorrow night, hopefully. Otherwise after the assembly this weekend.

**Comment by portlandpadre** [comment] 2020-08-20 01:55
Ok Friends.. this video Lag issue especially on the second display was killing me. AV brother insisted we only use jw library and not download the video and play thru VLC.. 
I went into the  control panel for my graphics card Nvidia Geoforce RTX added Jw library to list of customizable  apps. 

turned on V sync and triple buffering and BAm!!!! all lag and sync issue are gone. Also assigned the graphics card to always run the videos. I guess it might resort to only cpu for playback with integrated graphics? Regardless immediately cleared up issues.. 

My lag was super bad on the second display. and it is now gone.   I'm not a developer or anything just a friend who was going crazy with lag on the second display.

**Comment by AntonyCorbett** [comment] 2021-07-03 12:02
I am closing this now as there is no further feedback. Please feel free to reopen if needed.

**Closed by AntonyCorbett** 2021-07-03 12:02 UTC
Labels: question
